compatibility_date = "2024-11-29"
main = "src/index.js"
node_compat = true
workers_dev = false

[env.qa]
name = "u2f-qa"
route = { pattern = "https://api-qa.noman.land/u2f/v1/*", zone_name = "noman.land" }

[env.prod]
name = "u2f"
route = { pattern = "https://api.noman.land/u2f/v1/*", zone_name = "noman.land" }
