name = "u2f-service"
main = "src/index.js"
workers_dev = true
node_compat = true
compatibility_date = "2022-05-31"
route = { pattern = "https://api.noman.land/u2f/v1/*", zone_name = "noman.land" }

# [dev]
# local_protocol = "https"

# [env.prod]
# route = { pattern = "https://api.noman.land/u2f/v1/*", zone_name = "noman.land" }
