name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            npm install
            cp wrangler-example.toml wrangler.toml
            sed -i wrangler.toml -e 's/example1\.com/${{ secrets.DOMAIN1 }}/g' -e 's/example2\.com/${{ secrets.DOMAIN2 }}/g' -e 's/example3\.com/${{ secrets.DOMAIN3 }}/g' -e 's/example4\.com/${{ secrets.DOMAIN4 }}/g' -e 's/example5\.com/${{ secrets.DOMAIN5 }}/g'
          command: deploy
